### ISSUE TITLE
Something unexpected happened: TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by philipmjohnson** [smeijer/unimported#14]
I am trying to run unimported on our Meteor system but get the following error:

```
$ npx unimported
npx: installed 200 in 9.003s
something unexpected happened
TypeError: Cannot read property 'startsWith' of undefined
    at getDependencyName (/Users/philipjohnson/.npm/_npx/73288/lib/node_modules/unimported/dist/traverse.js:30:43)
    at Object.resolveImport (/Users/philipjohnson/.npm/_npx/73288/lib/node_modules/unimported/dist/traverse.js:44:28)
    at Object.<anonymous> (/Users/philipjohnson/.npm/_npx/73288/lib/node_modules/unimported/dist/meta.js:104:45)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/philipjohnson/.npm/_npx/73288/lib/node_modules/unimported/dist/meta.js:5:58)

```

You can reproduce the error by cloning/forking our repo at:

https://github.com/radgrad/radgrad2

and switching to the branch 'issue-344' which has package.json modified to provide the entry point for our Meteor app. 

Any help will be much appreciated!

**Comment by philipmjohnson** [comment]
Turns out I didn't understand the syntax of the "meteor" field in package.json.  For a typescript application, it should look like this:

```
  "meteor": {
    "mainModule": {
      "client": "client/main.ts",
      "server": "server/main.ts"
    }
  },
```

For javascript, it will be main.js.

**Comment by smeijer** [comment]
Thanks for coming back to this. I forgot that the Meteor docs are absent on this subject. It might be a good idea to add something more specific to the readme here.
